/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ECHO 0x2fffffff
#define ECHO_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define write 1
extern  int * write_1(char **, CLIENT *);
extern  int * write_1_svc(char **, struct svc_req *);
extern int chat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define write 1
extern  int * write_1();
extern  int * write_1_svc();
extern int chat_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
